export const PERSONAL_INFO = {
  name: 'Ranganathan Sadhula',
  shortName: 'Raghav',
  role: ['Full Stack Developer', 'AI / ML Engineer', 'Problem Solver'],
  company: 'AAVIL Inc',
  location: 'Vijayawada, Andhra Pradesh, India - 521225',
  tagline: 'Building intelligent digital experiences.',
  linkedin: 'https://www.linkedin.com/in/raghav-s-mr97/',
  github: 'https://github.com/RanganathanSadhula',
  portfolio: 'https://ranganathan.netlify.app/',
  email: 'ranganathansadhula@gmail.com',
  phone: '+91 7013608858',
  bio: `Junior Full Stack and AI/ML Developer at AAVIL Inc, passionate about building intelligent systems that solve real-world problems. 
  
Graduate of Lakireddy Bali Reddy College of Engineering (B.Tech CSE - AI & ML, CGPA 8.5/10, 2021-2025).

Winner of Best Final Year Project Award (NIT-2025), 2nd Prize at National Level Paper Presentation (GMRIT-2025), and 1st Prize at NEONITE-2k22.

Currently working on the RAG-based DataGlow.ai pipeline in production at AAVIL Inc, alongside other Full Stack and AI/ML projects involving LLM integrations and intelligent automation.`,
};

export const SKILLS = {
  frontend: [
    { name: 'React.js', level: 85 },
    { name: 'Next.js', level: 80 },
    { name: 'HTML / CSS', level: 90 },
    { name: 'JavaScript', level: 85 },
    { name: 'Webflow', level: 75 },
    { name: 'Tailwind CSS', level: 80 },
  ],
  backend: [
    { name: 'Node.js', level: 82 },
    { name: 'Python', level: 90 },
    { name: 'Flask', level: 85 },
    { name: 'Java', level: 80 },
    { name: 'REST APIs', level: 88 },
    { name: 'MySQL', level: 85 },
  ],
  aiMl: [
    { name: 'TensorFlow', level: 82 },
    { name: 'YOLOv5', level: 80 },
    { name: 'OpenCV', level: 78 },
    { name: 'NLP / NLU', level: 80 },
    { name: 'OpenAI API', level: 85 },
    { name: 'Deep Learning', level: 78 },
  ],
  databases: [
    { name: 'MySQL', level: 85 },
    { name: 'MongoDB', level: 75 },
    { name: 'PostgreSQL', level: 72 },
    { name: 'Firebase', level: 70 },
    { name: 'Databricks', level: 72 },
    { name: 'Apache Spark', level: 68 },
  ],
  devops: [
    { name: 'GitHub', level: 88 },
    { name: 'VS Code', level: 95 },
    { name: 'Raspberry Pi / IoT', level: 75 },
    { name: 'Docker', level: 65 },
    { name: 'Linux', level: 72 },
    { name: 'CI/CD', level: 65 },
  ],
  cloud: [
    { name: 'Microsoft Azure', level: 80 },
    { name: 'AWS', level: 70 },
    { name: 'Databricks', level: 72 },
    { name: 'Salesforce AI', level: 70 },
    { name: 'IBM Cloud', level: 65 },
    { name: 'Vercel / Netlify', level: 82 },
  ],
};

export const PROJECTS = [
  {
    id: 'dataglow-ai',
    title: 'DataGlow.ai — AI Data Readiness Platform',
    description: 'Production AI-powered data readiness and quality platform (RAG-based pipeline) built at AAVIL Inc. Features live monitoring dashboards, agentic workflow approvals, Databricks integration, and automated data quality scoring across enterprise datasets. Actively deployed in production.',
    tech: ['React', 'Vite', 'FastAPI', 'Node.js', 'Databricks', 'RAG', 'LangGraph'],
    github: 'https://github.com/RanganathanSadhula',
    demo: 'https://ranganathan.netlify.app/',
    color: '#10B981',
    category: 'AI / ML',
    featured: true,
    period: 'Apr 2026 – Present',
  },
  {
    id: 'ai-chatbot',
    title: 'AI Chatbot System',
    description: 'Deployed an intelligent AI-driven chatbot for Redfrencetech to automate customer interactions and improve support efficiency. Integrated NLP models for accurate intent detection and real-time conversational responses. Built backend to manage chat flow, process model predictions, and log interactions.',
    tech: ['Python', 'Flask', 'NLP', 'TensorFlow', 'REST API'],
    github: 'https://github.com/RanganathanSadhula',
    demo: 'https://ranganathan.netlify.app/',
    color: '#00D4FF',
    category: 'AI / ML',
    featured: true,
    period: 'Nov 2024 – Mar 2025',
  },
  {
    id: 'traffic-clearance',
    title: 'Traffic Clearance System for Ambulance',
    description: 'AI-powered traffic clearance system using YOLOv5 and LSTM for emergency vehicle detection. Integrated IoT sensors and Flask backend to automate traffic signal control, reducing emergency response time. Won Best Final Year Project Award at NIT-2025.',
    tech: ['Python', 'YOLOv5', 'OpenCV', 'IoT', 'Raspberry Pi', 'Flask', 'LSTM'],
    github: 'https://github.com/RanganathanSadhula',
    demo: 'https://lnkd.in/gEcKbB9t',
    color: '#EF4444',
    category: 'AI / ML',
    featured: true,
    period: 'Jan 2025 – Jun 2025',
  },
  {
    id: 'portfolio-pro',
    title: 'Portfolio Pro',
    description: 'Full-stack portfolio website with responsive design and seamless frontend-backend integration. Implemented admin dashboard for dynamic content updates and engineered a data management system to store and retrieve user messages in real-time.',
    tech: ['React.js', 'CSS3', 'HTML5', 'Node.js', 'MongoDB'],
    github: 'https://github.com/RanganathanSadhula',
    demo: 'https://ranganathan.netlify.app/',
    color: '#7C3AED',
    category: 'Full Stack',
    featured: true,
    period: 'Jan 2025 – Feb 2025',
  },
];

export const EXPERIENCE = [
  {
    id: 1,
    role: 'Junior Full Stack and AI/ML Developer',
    company: 'AAVIL Inc',
    location: 'India',
    period: 'Apr 2026 – Present',
    type: 'Full-time',
    description: 'Working as a Full Stack and AI/ML Developer, building intelligent web applications, LLM integrations, and scalable backend systems for enterprise clients.',
    achievements: [
      'Building full stack applications with React, Node.js, and Python',
      'Integrating AI/ML capabilities into production systems',
      'Completed Databricks Generative AI Fundamentals certification',
      'Completed Databricks Fundamentals certification',
      'Attended AI Isn\'t the Future — It\'s the Competitive Advantage of Today webinar',
    ],
    color: '#00D4FF',
  },
  {
    id: 2,
    role: 'AI & ML Intern',
    company: 'Taras Systems & Solutions',
    location: 'Chennai, Tamil Nadu (Remote)',
    period: 'Nov 2024 – May 2025',
    type: 'Internship',
    description: 'Planned and developed user-friendly responsive web designs (Student, Business, College portals) and built an intelligent AI chatbot for client automation.',
    achievements: [
      'Developed 3 responsive web designs using modern plugins and AI features',
      'Conducted user research for persona creation and UX optimization',
      'Built AI chatbot for Redfrencetech to automate customer support',
      'Designed wireframes and prototypes using best UX practices',
    ],
    color: '#7C3AED',
  },
  {
    id: 3,
    role: 'Artificial Intelligence Engineer Intern',
    company: 'MSsquare Technologies',
    location: 'Vizag, On-site',
    period: 'May 2024 – Jul 2024',
    type: 'Internship',
    description: 'Worked on AI & ML projects including AI Chat Bot and Sign Language Recognition systems.',
    achievements: [
      'Developed AI Chatbot system using Python and NLP',
      'Built Sign Language Recognition model using computer vision',
      'Gained hands-on experience with TensorFlow and OpenCV',
    ],
    color: '#F59E0B',
  },
  {
    id: 4,
    role: 'AICTC-Eduskills Virtual Internship',
    company: 'AWS Cloud Club GGSIPU',
    location: 'Remote',
    period: '2023 – 2024',
    type: 'Internship',
    description: 'Completed virtual internship focused on cloud technologies and data science.',
    achievements: [
      'Workshop on Data Science Using Python (Brainovision)',
      'Hands-On with IoT workshop (Smart Home & Industrial Limited)',
      'Gained AWS cloud fundamentals experience',
    ],
    color: '#10B981',
  },
];

export const CERTIFICATIONS = [
  { id: 1, title: 'Databricks Generative AI Fundamentals', issuer: 'Databricks Academy', date: '2026', color: '#FF6B35', icon: '🤖' },
  { id: 2, title: 'Databricks Fundamentals', issuer: 'Databricks Academy', date: '2026', color: '#FF6B35', icon: '📊' },
  { id: 3, title: 'Applied AI & ML Essentials', issuer: 'Vishlesan i-Hub, IIT Patna', date: '2025', color: '#7C3AED', icon: '🧠' },
  { id: 4, title: 'Azure Administrator Associate', issuer: 'Microsoft', date: '2023', color: '#0078D4', icon: '☁️' },
  { id: 5, title: 'ML Foundation Certification', issuer: 'Infosys Springboard', date: '2023', color: '#00D4FF', icon: '📐' },
  { id: 6, title: 'Salesforce Certified AI Associate', issuer: 'Salesforce', date: '2024', color: '#00A1E0', icon: '⚡' },
  { id: 7, title: 'Java Full Stack Global Certification', issuer: 'Wipro', date: '2024', color: '#9b59b6', icon: '☕' },
  { id: 8, title: 'Apache Spark for Data Engineering', issuer: 'IBM', date: '2024', color: '#1F70C1', icon: '🔥' },
  { id: 9, title: 'Programming Essentials in Python', issuer: 'Cisco Networking Academy', date: '2023', color: '#1BA0D7', icon: '🐍' },
  { id: 10, title: '160 Days Problem Solving', issuer: 'GeeksforGeeks', date: '2025', color: '#2F8D46', icon: '💻' },
];
